# Generated by Django 3.2.6 on 2021-08-16 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('inn', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('clientname', models.CharField(max_length=255, verbose_name='Client name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created datetime'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.client'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
