# Generated by Django 3.2.6 on 2021-08-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20210816_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='money',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
