# Generated by Django 3.2.6 on 2021-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20210824_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='clientname',
            field=models.CharField(max_length=255, verbose_name='clientname'),
        ),
    ]
